
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://llyylljrjcmopetidotx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxseXlsbGpyamNtb3BldGlkb3R4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3MTEyNDIsImV4cCI6MjA1ODI4NzI0Mn0.P0jMjibBIJ5pDJiySg90t6t_38vzPT_zYRHzwXZk_l4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    storage: localStorage,
  }
});
